### ISSUE TITLE
Error: invalid type: map, expected a sequence at line 1 column 1

### ISSUE THREAD

**Issue by PhillDubois** [DevYukine/rustfoil#12] opened 2023-08-28 11:37 UTC
Hi, I'm trying to use it on maxos (intel chip) and I'm having the error:

```bash
/ Scanned 0 file(s)
[Info] Parsed 0 file(s)
[Info] Generated index successfully
[Info] Finished writing index.tfl to disk, using ZSTD compression & no encryption
Error: invalid type: map, expected a sequence at line 1 column 1
```

The build I've used is `cargo build --release --target=x86_64-apple-darwin` then `./rustfoil --tinfoil-auth`

Can someone help me ?

**Comment by SphynxinatorX** [comment] 2023-09-07 12:48
There's issues parsing JSON when building for Mac.  I'm not really a rust dev but managed to fix it on my local branch.  I could fork and push the changes if you want.

You can also try this if you only want to generate a tinfoil token
https://sphynxinatorx.github.io/freefoil/

**Comment by DevYukine** [comment] 2023-11-19 18:05
Hey 👋 

This is likely caused by the old gdrive token/credentials format, this should be fixed in the latest version released today https://github.com/DevYukine/rustfoil/releases

**Closed by DevYukine** 2023-11-19 18:05 UTC
